### PR TITLE
Wrong 'error' variable is being read in socket_server.go

### PR DESCRIPTION
**Pull request by paulrd**
This is likely related to #125

### CODE REVIEW

**Comment by melekes** [comment]
not sure about this actually. see 83920a1c373d4e9c91b4f2d0f8ba3a40b8cdf5b0. @ebuchman /cc

**Comment by paulrd** [comment]
Yeah, see my discussion at #125. I think if you had a blocking read (in HandleRequests), you should never get EOF until the connection is closed (by client) so that return statement might make sense. As it is now, you can get EOF when the next message hasn't arrived from the client yet (IIUC).

**Comment by melekes** [comment]
this change breaks the code. if you try running TM and abci-cli, TM will fail with "Connection was closed by client" error. the original code is correct.

**Comment by paulrd** [comment]
That's strange, the only effect this code should have would be in the error message logged. Isn't TM the client? It's the abci-cli (dummy or counter) app (server) that will 'fail' with "Connection was closed by client". EOF gets detected with a different message in the very next clause of the if statement anyway. So instead of "Connection was closed by client" you get "Connection error module=abci-server error=EOF". This pull request doesn't change the logic of the abci-server at all. Checking err instead of errClose is clearly a bug (if not a very severe one). Why would you want to check err here anyway?

**Comment by ebuchman** [comment]
This was clearly a bug. Thanks for finding and fixing it! Sorry for delays/confusion :)

**Pull request merged**
