### PR TITLE
v0.3.0, for Tendermint v0.8.0

### PR DESCRIPTION
**Pull request by ebuchman**
- BeginBlock takes a Header
- Info returns last block height and app hash
- Persistent Dummy uses Info/BeginBlock to recover from failures
- Hex strings are 0x prefixed

### CODE REVIEW

**Comment by anthonymoralez** [comment]
Any word on when this will be incorporated into the master branch?

**Comment by ebuchman** [comment]
imminently. part of the issue is I've been on vacation for two days and haven't had a good stretch of time to buckle down and finalize the 0.8 release. hopefully we can get it done by mid next week.

**Comment by tomtruitt** [comment]
wait is this the changelog? do you guys post a changelog anywhere?

**Comment by ebuchman** [comment]
Updated PR comment to be a changelog

**Pull request merged**
