### PR TITLE
Add InitialValSet and AppHash to ResponseInitChain

### PR DESCRIPTION
**Pull request by adrianbrink**

### CODE REVIEW

**Comment by melekes** [comment]
You forgot to regenerate `types/types.pb.go` (`make get_protoc && make protoc`)

**Comment by ebuchman** [comment]
Let's put the entire Genesis structure in protobuf and include that? 

https://github.com/tendermint/abci/issues/216

**Comment by adrianbrink** [comment]
I don't think we need the entire genesis.json structure. What's the advantage of including everything?

**Comment by melekes** [comment]
Refs https://github.com/tendermint/tendermint/issues/1271

**Pull request closed without merging**
