### PR TITLE
Change evidence type to enum

### PR DESCRIPTION
**Pull request by cwgoes**
Ref https://github.com/cosmos/cosmos-sdk/pull/1011#discussion_r191904300

### CODE REVIEW

**Comment by cwgoes** [comment]
Probably we should update Tendermint/SDK to latest ABCI develop first.

**Comment by ebuchman** [comment]
I think a string would actually be best, like in PubKey now.

A pubkey assumes data is just bytes. For Evidence we assume data includes a pubkey, height, and time, but otherwise the type doesnt change the kind of information included.

Using a string could allow the type to take hierarchical form - "equivocation/proposal" or "invalid/proposal/signature".

If we need to provide even more information, we can later add a `bytes data` field and let the type string also inform us how it's encoded ...

**Comment by cwgoes** [comment]
Can we include some constant types in this repository then, or find some other way to import a common set in Tendermint and the SDK?

**Comment by ebuchman** [comment]
Yep let's add the type strings to tendermint/types/evidence.go

**Comment by cwgoes** [comment]
Great, closing in favor of https://github.com/tendermint/tendermint/pull/1652

**Pull request closed without merging**
