### PR TITLE
Upgrade grpc and protobuf to latest version

### LINKED ISSUE #248: Not only use minor version for grpc dependency
grpc lib is a common library in many golang application, right now abci can be conflict with others when other application use higher grpc version. I'd like to remove this limitation.

### PR DESCRIPTION
**Pull request by GrapeBaBa**
Avoid conflict with other lib, upgrade grpc lib to latest version. It fixed #248 
Signed-off-by: grapebaba <281165273@qq.com>

### CODE REVIEW

**Review by melekes — APPROVED** [review]

**Comment by ebuchman** [comment]
Thanks for this. Reverted gogoproto removal so we could merge the API changes through first. 

Will reremove gogoproto shortly, then merge this. Thanks

**Comment by GrapeBaBa** [comment]
@ebuchman how is going？

**Comment by zramsay** [comment]
@GrapeBaBa the whole abci repo has been merged into the tendermint repo. We welcome a new PR there with this fix. Thanks and sorry for the delay

**Comment by ebuchman** [comment]
@GrapeBaBa I tried applying these changes now that ABCI is moved into Tendermint and the Tendermint gRPC test failed. Maybe you could take a look? See https://github.com/tendermint/tendermint/issues/1944

**Pull request closed without merging**
