### PR TITLE
Add counter binary to demo application fully

### PR DESCRIPTION
**Pull request by ethanfrey**
Gautier was looking at the abci repo to follow up from Adrian's talk and understand the abci structure.

While there are some example apps, there is no code to show how to actually run them. Nor are they commented.

I added a simple, commented main package for counter, which one can connect to via abci-cli. I thought there were apps like this before. We definitely need better documentation here if we point new developers to this package.

### CODE REVIEW

**Comment by zramsay** [comment]
https://github.com/tendermint/abci/blob/master/cmd/abci-cli/abci-cli.go#L418-L440

**Comment by zramsay** [comment]
arguably the read the docs doc should be rendered from this repo's readme.rst, like we do with tools

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/abci/issues/134

**Comment by zramsay** [comment]
@melekes yes, doing that now. Will add to https://github.com/tendermint/tendermint/pull/1046

**Pull request closed without merging**
