### PR TITLE
Use gogoproto's nullable=false

### PR DESCRIPTION
**Pull request by jaekwon**
Avoiding pointers where it isn't necessary is generally better for security, as non-pointer/non-addressable values are immutable.

Also, some of our proto fields just shouldn't be nullable.

This PR addresses both issues.

### CODE REVIEW

**Comment by ethanfrey** [comment]
Jae, while you are looking at protobuf format (and I agree with these changes), can you check out #165 ? I think it would be nice to express all Responses like (DeliverTxResponse, error), with a litlte adjustment to protobuf, we can add a simple golang function to extract the values from a Response into a more golang-esce format, and make us all hate protobuf just a little bit less.

**Comment by jaekwon** [comment]
@ethanfrey Yeah of course, I will look at it in the next 10 hours.

**Comment by jaekwon** [comment]
@ethanfrey Done, I responded there!

**Comment by odeke-em** [comment]
@jaekwon, here is a little counter. The problems with non-pointers are that:
* now we can't tell if something was set or not
* all data fields will be sent across the wire irrespective of if they are nil or not -- bandwidth wastage
* Lots of data copying when we invoke methods and functions
* the idea of being immutable might be a fallacy: for sure it provides security with args passed into when functions(however is this the common usage pattern?) vs normal usage(code in a common function where mutability will apply irrespective of if a pointer or not)
```go
func fooWithPointer(b *Bar) {
   b.Time = time.Now()
}

// Security safe pattern, awesome
func fooWithoutPointer(b Bar) {
   b.Time = time.Now()
}

func zip(b Bar) {
   b.Time = time.Now()
   // do more stuff with b
   if b.Time.After(aLongTimeAgo) {
   }
   // Irrespective of if b was a pointer or not, we've mutated it
}
```
is `zip` the common usage pattern in our code?

**Pull request merged**
